name: 'oxs-package-version'
description: 'Updates a package version in the manifest file.'

branding:
  icon: log-in
  color: 'blue'

inputs: 
  mainFolder:
    description: 'The repository and the main folder where to find the sub folders.'
    required: true

  packageFolders:
    description: 'A list of folders where are the manifest files'
    required: true
    
  branch:
    description: 'The current branch, main or production.'
    required: true

  github_token:
    description: 'GitHub token for authentication'
    required: true
    default: ''

  bearer_token:
    description: 'Bearer token for oxs authentication'
    required: true
  
  api_url:
    description: 'The url which api environment (main, production) will be called'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        ref: "${{ github.base_ref }}" # This ensures you check out the branch where the PR is pushed

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run Python script to update version
      shell: bash
      run: |
        for package in ${{ inputs.packageFolders }}; do
          python ${{ github.action_path }}/update_version_number.py ${{ inputs.mainFolder }}$package/manifest.json ${{ inputs.branch }} ${{ inputs.bearer_token }} ${{ inputs.api_url }}
          git add ${{ inputs.mainFolder }}$package/manifest.json
        done

    - name: Commit version update
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update version from packages: ${{ inputs.packageFolders }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
