name: 'oxs-package-version'
description: 'Updates a package version in the manifest file.'

branding:
  icon: log-in
  color: 'blue'

inputs: 
  mainFolder:
    description: 'The repository and the main folder where to find the sub folders.'
    required: true

  packageFolders:
    description: 'A list of folders where are the manifest files'
    required: true
    
  branch:
    description: 'The current branch, main or production.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run Python script to update version
      shell: bash
      run: |
        for package in ${{ inputs.packageFolders }}; do
          python ${{ github.action_path }}/update_version_number.py ${{ inputs.mainFolder }}$package/manifest.json ${{ inputs.branch }}
          git add ${{ inputs.mainFolder }}$package/manifest.json
        done

    - name: Commit version update
      uses: EndBug/add-and-commit@v7
      with:
        message: "Update version from packages: ${{ inputs.packageFolders }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
